#!/bin/sh

die() {
    printf "$0: %s\n" "$@" 1>&2
    exit 1
}

tmp="$(mktemp -d "${TMPDIR:-/tmp}/pandoc-rss.XXXXXXXX")"

printf '%s\n' '$meta-json$' > "$tmp/template.json"

cat > "$tmp/template.xml" <<'EOF'
<item>
<title>$title$</title>
<link>$linkprefix$</link>
<guid>$linkprefix$</guid>
$if(description)$
<description>$description$</description>
$endif$
<pubDate>$date$</pubDate>
</item>
EOF

while :; do
    case "$1" in
    -f|--format)
        format="$2"
        shift 2
        ;;
    -h|--help)
        die 'Usage: pandoc-rss -f FORMAT FILE [FILE ...]'
        ;;
    --)
        shift
        break
        ;;
    -*)
        die "No such option ‘$1’"
        ;;
    *)
        break
        ;;
    esac
done

[ -n "$format" ] || die 'Please specify a format string.'

for i in "$@"; do
    date="$(pandoc --template="$tmp/template.json" "$i" | jq -r .date)"
    date="$(date -u -d "$date" '+%a, %d %b %Y %T UTC')"
    basename="$(basename "$i" | sed 's/\.\w\+$//')"
    linkprefix="$(printf "$format" "$basename")"
    pandoc --template="$tmp/template.xml" \
      -V "linkprefix:$linkprefix" "$i" \
      -V "date:$date"
done

rm -r "$tmp"
