.TH PANDOC\-RSS 1 "July 2020"
.SH NAME
pandoc\-rss \- Generate an RSS feed using Pandoc
.SH SYNOPSIS
.PP
pandoc\-rss [\f[I]options\f[]] [\f[I]input\-file\f[]]...
.PP
pandoc\-rss \-s [\f[I]options\f[]] [\f[I]input\-file\f[]]... > feed.xml
.SH DESCRIPTION
.PP
The
.B pandoc\-rss
utility can be used to generate an RSS feed from a series of input
files.  Each \f[I]input\-file\f[] corresponds to a feed item, and must
be written in a markup language that can be read by Pandoc.
.SH OPTIONS
.TP
\-g \f[I]FORMAT\f[]
Include guid elements. The printf\-style
.I FORMAT
string should contain exactly one \[oq]%s\[cq] which will be
substituted for the file name of
.I input\-file
stripped of its extension.
.IP
For example, if
.I FORMAT
is \f[C]http://example.net/%s.html\f[], then an
\f[I]input\-file\f[] named \[oq]foo.md\[cq] will have a guid
element containing \[oq]http://example.net/foo.html\[cq].
.TP
\-s
Produce a standalone XML file that represents an entire feed.
(By default, only item fragements are produced.)
.SH EXIT STATUS
.SH ENVIRONMENT
.SH NOTES
.SH BUGS
.SH EXAMPLES
.IP
.nf
\f[C]
pandoc\-rss \-sg http://example.net/%s.html foo.md bar.md
\f[R]
.fi
.SH AUTHORS
.SH SEE ALSO
